---
title: 04函数

date: 2022-02-24	

categories: Go笔记	

tags: [Go知识点,Go笔记]
---	

# 函数声明

实参通过值的方式传递，因此函数的形参是实参的**值拷贝**。**形参进行修改不会影响实参**。但是，**如果实参包括引用类型**，如指针，slice(切片)、map、function、channel等类型，**实参可能会由于函数的间接引用被修改**。

拥有2个int型参数和1个int型返回值的函数（__符号：强调某个参数未被使用）

```Go
func add(x int, y int) int   {return x + y}
func sub(x, y int) (z int)   { z = x - y; return}
func first(x int, _ int) int { return x }
func zero(int, int) int      { return 0 }
```

# 错误

```Go
func main() {
	resp, err := http.Get(url)
	if err != nil {
		fmt.Println(err)
	}
}

func WaitForServer(url string) error {
    const timeout = 1 * time.Minute
    deadline := time.Now().Add(timeout)
    for tries := 0; time.Now().Before(deadline); tries++ {
        _, err := http.Head(url)
        if err == nil {
            return nil // success
        }
        log.Printf("server not responding (%s);retrying…", err)
        time.Sleep(time.Second << uint(tries)) // exponential back-off
    }
    return fmt.Errorf("server %s failed to respond after %s", url, timeout)
}
```

```Go
if err := WaitForServer(url); err != nil {
    fmt.Fprintf(os.Stderr, "Site is down: %v\n", err)
    os.Exit(1)
    
    log.Fatalf("Site is down: %v\n", err)
}
```

如果错误的发生是偶然性的，或由不可预知的问题导致的。一个明智的选择是重新尝试失败的操作。在重试时，我们需要限制重试的时间间隔或重试的次数，防止无限制的重试。

**log**中的所有函数，都默认会在错误信息之前**输出时间信息**。

# 函数值

在Go中，函数被看作第一类值（first-class values）：函数像其他值一样，拥有类型，可以被赋值给其他变量，传递给函数，从函数返回。对函数值（function value）的调用类似函数调用.

```Go
func square(n int) int { return n * n }
func negative(n int) int { return -n }

f := square
fmt.Println(f(3)) // "9"

f = negative
fmt.Println(f(3))     // "-3"
fmt.Printf("%T\n", f) // "func(int) int"
```

函数类型的零值是nil。调用值为nil的函数值会引起panic错误：

```Go
var f func(int) int
f(3) // 此处f的值为nil, 会引起panic错误
```

函数值之间是不可比较的，也不能用函数值作为map的key。

# 匿名函数

func关键字后没有函数名。函数值字面量是一种表达式，它的值被称为匿名函数，函数字面量允许我们在使用函数时，再定义它。

通过这种方式定义的函数可以访问完整的词法环境（lexical environment），这意味着在函数中定义的内部函数可以引用该函数的变量：

```Go
func squares() func() int {
    var x int
    return func() int {
        x++
        return x * x
    }
}
func main() {
    f := squares()
    fmt.Println(f()) // "1"
    fmt.Println(f()) // "4"
    fmt.Println(f()) // "9"
    fmt.Println(f()) // "16"
}
```

==Go使用闭包（closures）技术实现函数值，Go程序员也把函数值叫做闭包，等待循环结束后，再执行函数值。==

# 可变参数

在声明可变参数函数时，需要在参数列表的最后一个参数类型之前加上省略符号`...`，这表示该函数会接收任意数量的该类型参数。

```Go
func sum(vals...int) int {
    total := 0
    for _, val := range vals {
        total += val
    }
    return total
}
```

sum函数返回任意个int型参数的和。在函数体中,vals被看作是类型为[] int的切片。sum可以接收任意数量的int型参数：

```Go
fmt.Println(sum())           // "0"
fmt.Println(sum(3))          // "3"
fmt.Println(sum(1, 2, 3, 4)) // "10"
```

# Deffered函数

你只需要在调用普通函数或方法前加上关键字**defer**，当执行到该条语句时，函数和参数表达式得到计算，但直到包含该defer语句的**函数执行完毕**时，**defer后的函数才会被执行**，可以在一个函数中执行**多条defer语句**，它们的**执行顺序与声明顺序相反**。

# Panic异常

虽然Go的panic机制类似于其他语言的异常，但panic的适用场景有一些不同。由于panic会引起程序的崩溃，因此panic一般用于严重错误，如程序内部的逻辑不一致。勤奋的程序员认为任何崩溃都表明代码中存在漏洞，所以对于大部分漏洞，我们应该使用Go提供的错误机制，而不是panic，尽量避免程序的崩溃。在健壮的程序中，任何可以预料到的错误，如不正确的输入、错误的配置或是失败的I/O操作都应该被优雅的处理，最好的处理方式，就是使用Go的错误机制。

# Recover捕获异常

如果在deferred函数中调用了内置函数recover，并且定义该defer语句的函数发生了panic异常，recover会使程序从panic中恢复，并返回panic value。导致panic异常的函数不会继续运行，但能正常返回。在未发生panic时调用recover，recover会返回nil。

```Go
func Parse(input string) (s *Syntax, err error) {
    defer func() {
        if p := recover(); p != nil {
            err = fmt.Errorf("internal error: %v", p)
        }
    }()
    // ...parser...
}
```
